spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

datasources:
  write:
    url: jdbc:mysql://127.0.0.1:13306/tx_db
    user-name: root
    password: 123456
  read:
    url: jdbc:mysql://127.0.0.1:13307/tx_db
    user-name: root
    password: 123456